export { d as assets, b as assetsBuildDirectory, c as basename, e as entry, f as future, i as isSpaMode, m as mode, p as publicPath, r as routes } from './assets/server-build-D5H6ZeJU.js';
import 'react/jsx-runtime';
import '@remix-run/react';
import 'isbot';
import 'react-dom/server';
import 'remix-island';
import 'nanostores';
import '@remix-run/cloudflare';
import 'ai';
import 'node:process';
import '@ai-sdk/anthropic';
import 'rehype-sanitize';
import 'remix-utils/client-only';
import 'react';
import '@nanostores/react';
